"""Alert File Writer for Silver Tier.

Creates alert files in /Vault/Alerts/ to notify users of:
- Tampered approval files (security critical)
- OAuth token refresh failures
- Memory budget exceeded warnings
- Watcher process failures

Alerts are Markdown files with clear action items for the user.
"""

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from src.common.vault import get_vault, Vault

logger = logging.getLogger(__name__)


class AlertSeverity:
    """Alert severity levels."""
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


class AlertType:
    """Predefined alert types."""
    TAMPERED_APPROVAL = "tampered_approval"
    OAUTH_FAILURE = "oauth_failure"
    MEMORY_WARNING = "memory_warning"
    MEMORY_CRITICAL = "memory_critical"
    WATCHER_DOWN = "watcher_down"
    DATABASE_ERROR = "database_error"
    RATE_LIMIT_HIT = "rate_limit_hit"
    INTEGRITY_VIOLATION = "integrity_violation"
    API_ERROR = "api_error"


def _get_severity_emoji(severity: str) -> str:
    """Get emoji for severity level."""
    return {
        AlertSeverity.INFO: "ℹ️",
        AlertSeverity.WARNING: "⚠️",
        AlertSeverity.ERROR: "❌",
        AlertSeverity.CRITICAL: "🚨",
    }.get(severity, "📢")


def _get_alert_filename(alert_type: str, timestamp: datetime) -> str:
    """Generate filename for alert."""
    date_str = timestamp.strftime("%Y-%m-%d_%H%M%S")
    return f"{date_str}_{alert_type}.md"


def _format_alert_content(
    alert_type: str,
    title: str,
    message: str,
    severity: str,
    timestamp: datetime,
    details: dict[str, Any] | None = None,
    actions: list[str] | None = None
) -> str:
    """Format alert content as Markdown.

    Args:
        alert_type: Type of alert
        title: Alert title
        message: Alert message
        severity: Severity level
        timestamp: When the alert was created
        details: Optional additional details
        actions: Optional list of recommended actions

    Returns:
        Markdown content
    """
    emoji = _get_severity_emoji(severity)

    content = f"""---
alert_type: {alert_type}
severity: {severity}
timestamp: {timestamp.isoformat()}
acknowledged: false
---

# {emoji} {title}

**Severity**: {severity.upper()}
**Time**: {timestamp.strftime("%Y-%m-%d %H:%M:%S UTC")}
**Type**: {alert_type}

## Message

{message}
"""

    if details:
        content += "\n## Details\n\n"
        for key, value in details.items():
            display_key = key.replace("_", " ").title()
            content += f"- **{display_key}**: {value}\n"

    if actions:
        content += "\n## Recommended Actions\n\n"
        for i, action in enumerate(actions, 1):
            content += f"{i}. {action}\n"

    content += f"""
---

*To acknowledge this alert, add `acknowledged: true` to the frontmatter or delete this file.*
*Alert generated by AI Employee at {timestamp.strftime("%Y-%m-%d %H:%M:%S UTC")}*
"""

    return content


async def create_alert(
    alert_type: str,
    title: str,
    message: str,
    severity: str = AlertSeverity.WARNING,
    details: dict[str, Any] | None = None,
    actions: list[str] | None = None,
    vault: Vault | None = None
) -> Path:
    """Create an alert file in /Vault/Alerts/.

    Args:
        alert_type: Type of alert (use AlertType constants)
        title: Human-readable alert title
        message: Detailed message explaining the issue
        severity: Alert severity (use AlertSeverity constants)
        details: Optional additional details as key-value pairs
        actions: Optional list of recommended actions for the user
        vault: Vault instance (default: from env)

    Returns:
        Path to the created alert file
    """
    vault = vault or get_vault()
    timestamp = datetime.now(timezone.utc)

    # Generate content
    content = _format_alert_content(
        alert_type=alert_type,
        title=title,
        message=message,
        severity=severity,
        timestamp=timestamp,
        details=details,
        actions=actions
    )

    # Generate filename
    filename = _get_alert_filename(alert_type, timestamp)

    # Write file
    alert_path = vault.write_file("alerts", filename, content)

    logger.warning(f"Alert created: [{severity.upper()}] {title} -> {alert_path}")

    return alert_path


def create_alert_sync(
    alert_type: str,
    title: str,
    message: str,
    severity: str = AlertSeverity.WARNING,
    details: dict[str, Any] | None = None,
    actions: list[str] | None = None,
    vault: Vault | None = None
) -> Path:
    """Synchronous version of create_alert."""
    import asyncio
    return asyncio.run(create_alert(
        alert_type, title, message, severity, details, actions, vault
    ))


# Convenience functions for common alerts

async def alert_tampered_approval(
    filename: str,
    expected_hash: str,
    vault: Vault | None = None
) -> Path:
    """Create alert for tampered approval file."""
    return await create_alert(
        alert_type=AlertType.TAMPERED_APPROVAL,
        title="Tampered Approval File Detected",
        message=f"The approval file `{filename}` was modified after creation. "
                f"The integrity hash no longer matches, indicating the file was tampered with. "
                f"The action was **NOT executed** for security reasons.",
        severity=AlertSeverity.CRITICAL,
        details={
            "filename": filename,
            "expected_hash_prefix": expected_hash[:16] + "...",
            "action_taken": "File moved to Rejected folder with _TAMPERED prefix"
        },
        actions=[
            "Review the rejected file to understand what was changed",
            "If the action is still needed, create a new approval request",
            "Investigate who or what modified the file",
            "Consider enabling file monitoring/auditing on the vault folder"
        ],
        vault=vault
    )


async def alert_oauth_failure(
    service: str,
    error: str,
    retry_count: int,
    vault: Vault | None = None
) -> Path:
    """Create alert for OAuth token refresh failure."""
    return await create_alert(
        alert_type=AlertType.OAUTH_FAILURE,
        title=f"{service.title()} Authentication Failed",
        message=f"Failed to refresh OAuth token for {service} after {retry_count} attempts. "
                f"The watcher has been paused until authentication is restored.",
        severity=AlertSeverity.ERROR,
        details={
            "service": service,
            "error": error,
            "retry_attempts": retry_count,
            "watcher_status": "paused"
        },
        actions=[
            f"Run the authentication setup script: `python scripts/setup_{service}_oauth.py`",
            f"Check that your {service} API credentials are still valid",
            f"Restart the watcher after re-authenticating: `pm2 restart {service}-watcher`"
        ],
        vault=vault
    )


async def alert_memory_warning(
    current_usage_mb: float,
    budget_mb: float,
    watcher_usage: dict[str, float],
    vault: Vault | None = None
) -> Path:
    """Create alert for memory budget warning."""
    percent = (current_usage_mb / budget_mb) * 100

    return await create_alert(
        alert_type=AlertType.MEMORY_WARNING,
        title="Memory Usage Warning",
        message=f"Total watcher memory usage has reached {current_usage_mb:.1f}MB "
                f"({percent:.0f}% of {budget_mb}MB budget). "
                f"If usage continues to increase, low-priority watchers may be paused.",
        severity=AlertSeverity.WARNING,
        details={
            "current_usage_mb": f"{current_usage_mb:.1f}",
            "budget_mb": budget_mb,
            "usage_percent": f"{percent:.0f}%",
            **{f"{name}_usage_mb": f"{mb:.1f}" for name, mb in watcher_usage.items()}
        },
        actions=[
            "Review watcher logs for memory leaks",
            "Consider increasing poll intervals to reduce memory churn",
            "Restart watchers to free memory: `pm2 restart all`",
            "If issue persists, increase memory budget in watcher_config.yaml"
        ],
        vault=vault
    )


async def alert_memory_critical(
    current_usage_mb: float,
    budget_mb: float,
    paused_watchers: list[str],
    vault: Vault | None = None
) -> Path:
    """Create alert for critical memory situation."""
    return await create_alert(
        alert_type=AlertType.MEMORY_CRITICAL,
        title="Memory Budget Exceeded - Watchers Paused",
        message=f"Total memory usage ({current_usage_mb:.1f}MB) has exceeded the budget "
                f"({budget_mb}MB). Low-priority watchers have been paused to protect system stability.",
        severity=AlertSeverity.CRITICAL,
        details={
            "current_usage_mb": f"{current_usage_mb:.1f}",
            "budget_mb": budget_mb,
            "paused_watchers": ", ".join(paused_watchers) if paused_watchers else "none"
        },
        actions=[
            "Restart watchers to free memory: `pm2 restart all`",
            "Check for memory leaks in watcher processes",
            "Consider reducing the number of active watchers",
            "Increase system memory or adjust budget in watcher_config.yaml"
        ],
        vault=vault
    )


async def alert_watcher_down(
    watcher_name: str,
    error: str | None = None,
    vault: Vault | None = None
) -> Path:
    """Create alert for watcher process failure."""
    return await create_alert(
        alert_type=AlertType.WATCHER_DOWN,
        title=f"{watcher_name.replace('_', ' ').title()} Watcher Down",
        message=f"The {watcher_name} watcher has stopped unexpectedly. "
                f"Events will not be detected until the watcher is restarted.",
        severity=AlertSeverity.ERROR,
        details={
            "watcher": watcher_name,
            "error": error or "Unknown error",
            "time_down": datetime.now(timezone.utc).isoformat()
        },
        actions=[
            f"Check watcher logs: `pm2 logs {watcher_name}`",
            f"Restart the watcher: `pm2 restart {watcher_name}`",
            "Review the error message for root cause",
            "Check system resources (memory, disk space)"
        ],
        vault=vault
    )


async def alert_rate_limit_hit(
    service: str,
    action_type: str,
    current_count: int,
    max_count: int,
    vault: Vault | None = None
) -> Path:
    """Create alert for rate limit reached."""
    return await create_alert(
        alert_type=AlertType.RATE_LIMIT_HIT,
        title=f"{service.title()} Rate Limit Reached",
        message=f"The daily rate limit for {action_type} on {service} has been reached. "
                f"Further requests will be queued until tomorrow.",
        severity=AlertSeverity.INFO,
        details={
            "service": service,
            "action_type": action_type,
            "current_count": current_count,
            "max_count": max_count,
            "reset_time": "Midnight UTC"
        },
        actions=[
            "Wait until the rate limit resets at midnight UTC",
            "Review approved actions to ensure they are necessary",
            "Consider increasing rate limits in watcher_config.yaml if needed"
        ],
        vault=vault
    )
